version: '3'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "max_connections=200"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  books-service:
    build:
      context: ./books
    depends_on:
      - postgres
    environment:
      POSTGRES_URI: "postgres://admin:admin@postgres:5432/books?sslmode=disable"
    ports:
      - "8082:8082"

  profile-service:
    build:
      context: ./profile
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - books-service
      - profile-service
      
  # Service running pytest to test the REST API
  pytest:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - postgres
      - api-gateway
    volumes:
      - .:/app
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; ptw tests'
    # command: ["ptw", "tests"]

volumes:
  postgres_data: