FROM python:3.9

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the test files
COPY . /app

# Run pytest with pytest-watch
CMD ["ptw", "tests"]
